name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '26 5 * * 6'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install @microsoft/eslint-formatter-sarif
        run: |
          npm install @microsoft/eslint-formatter-sarif@3.0.0

      - name: Run ESLint
        run: npx eslint .
          --ext .js,.jsx,.ts,.tsx,.cjs,.mjs
          --format @microsoft/eslint-formatter-sarif 
          --output-file eslint-results.sarif
          --report-unused-disable-directives
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
